### ISSUE TITLE
[New Fix] Automatically update name of deployed craft to reference the deploying vessel's name

### ISSUE THREAD

**Issue by schlosrat** [KSP2Community/CommunityFixes#23]
**What will the fix solve? Please describe.**
Currently, when deploying one vessel from another the deployed craft gets a name like "Default Name-4". This is just silly and far from useful.

**Describe the solution you'd like**
When one craft is deployed from another, it would be nice if there deployed craft took on a name like "<Deploying Vessel Name> Probe-1", and so forth. If the separated object has a drone core or command pod in it, then it should be named as a "probe" or something like that (perhaps configurable through mod settings?), and if it doesn't have a drone core or command pod, then it should be marked as "Debris" without bothering to include the deploying vessel's base name.

**Additional context**
Perhaps this can be piggybacked with the fix that corrects loss of comm net for deployed craft? If we're fixing that, it might be a good opportunity to fix the name too.

**Comment by jan-bures** [comment]
Good idea, I'll take a look at it, since it will also be useful for another mod I'm currently working on

**Comment by Lentigos** [comment]
Hey I'm new to this whole thing but I have a small issue:

When pausing and unpausing, the game sends several messages instead of one. I thought that might be easily fixable. One time I received 8 messages at once, all saying the game was paused.

Thx.

**Comment by jan-bures** [comment]
> Hey I'm new to this whole thing but I have a small issue:
> 
> When pausing and unpausing, the game sends several messages instead of one. I thought that might be easily fixable. One time I received 8 messages at once, all saying the game was paused.
> 
> Thx.

Sorry for the (very) late reply, this seems to no longer be an issue in the game.

**Comment by jan-bures** [comment]
Naming of decoupled and docked/undocked vessels fixed in #44.
