### ISSUE TITLE
[New Fix] Enable Kerbal Suit EVA lights

### ISSUE THREAD

**Issue by schlosrat** [KSP2Community/CommunityFixes#24]
**What will the fix solve? Please describe.**
Currently, Kerbals on EVA are unable to have their suit lights switched on

**Describe the solution you'd like**
We should not leave them in the dark. Please help bring them into the light!

**Additional context**
Come toward the light, Marianne! Come toward the light!

**Comment by jan-bures** [comment]
Now there's a mod that enables this! https://github.com/WiS3/KerbalHeadlamp
