### ISSUE TITLE
VesselLandedStateFix possible issue

### ISSUE THREAD

**Issue by charles815** [KSP2Community/CommunityFixes#45]
Every once in a while I get an odd bounce when landing and I'm wondering if the code in this fix is causing the issue.  There's a check to to see if vessel.AltitudeFromTerrain is above 50.  When testing on the runway, this value returns 282.  During a takeoff roll, this code is triggered many times.  Should the code check AltitudeFromSurface instead?  What is the difference between AltitudeFromTerrain and AltitudeFromSurface?

**Comment by jan-bures** [comment]
The code should not be affecting any physical properties of the craft at all, only the "theoretical" state that the game considers the vessel to be in, so I don't think this could be causing any sort of bouncing. But to make sure, could you please try to test this with and without the fix enabled?

However, you are correct in that I should be using AltitudeFromSurface for better accuracy, thanks for letting me know, I'll switch to that in the next update.

**Comment by jan-bures** [comment]
After checking this again, I cannot verify any sort of correlation between any physical occurrences such as landing gear bounces and this fix. The AltitudeFromSurface change will be implemented in the next release.
